const mongoose = require('mongoose');

const AirbnbSchema = new mongoose.Schema({
    _id: String,
    listing_url: String,
    name: String,
    summary: String,
    space: String,
    description: String,
    neighborhood_overview: String,
    notes: String,
    transit: String,
    access: String,
    interaction: String,
    house_rules: String,
    property_type: String,
    room_type: String,
    bed_type: String,
    minimum_nights: String,
    maximum_nights: String,
    cancellation_policy: String,
    accommodates: Number,
    bedrooms: Number,
    beds: Number,
    bathrooms: mongoose.Schema.Types.Decimal128,
    amenities: [String],
    price: mongoose.Schema.Types.Decimal128,
    security_deposit: mongoose.Schema.Types.Decimal128,
    cleaning_fee: mongoose.Schema.Types.Decimal128,
    extra_people: mongoose.Schema.Types.Decimal128,
    guests_included: mongoose.Schema.Types.Decimal128,
    images: Object,
    host: Object,
    address: Object,
    availability: Object,
    review_scores: Object,
    reviews: [Object],
}, { timestamps: true });

module.exports = mongoose.model('Listing', AirbnbSchema, "listingsAndReviews");